name: "array to json"

on:
  workflow_dispatch:
    inputs:
      test: 
        default: '["identity", "network", "security", "storage", "operations"]'
      workspaces:
        description: 'Workspaces to rebuild [ identity | network | security | storage | operations]'
        required: true
        default: 'identity, network, security, storage, operations'
jobs:
  test_pipeline_exitcodes_succeed:
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.array2json.outputs.result }}
    steps:
      - uses: actions/github-script@v3
        id: array2json
        with:
          script: |
            var base_array = '${{ github.event.inputs.workspaces }}'
            var arr = base_array.split(",").map(function(item) {
              return item.trim();
            });
            return JSON.stringify(arr);
      - name: print
        run: |
          echo "${{ github.event.inputs.test }}"
          echo "${{ steps.array2json.outputs.result }}"
  matrix_job:
    runs-on: ubuntu-latest    
    needs: [ test_pipeline_exitcodes_succeed ]
    strategy:
      fail-fast: false
      matrix: 
        workspace: ${{ fromJson(needs.test_pipeline_exitcodes_succeed.outputs.workspaces) }}
    steps:
      - run: echo "${{ matrix.workspace }}"
