
name: Matrix
on: workflow_dispatch
jobs:
  matrix-job:
    name: matrix-job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: 
        value: ['one', 'two', 'three', 'four', 'five']
    steps:
      - name: test_matrix
        id: test
        run: |
          sleep 10s
          echo ${{ matrix.value }}
