
name: Matrix
on: 
  workflow_dispatch:
    inputs:
      COMMAND:
        description: 'command'
        required: true
      MAX_PARALLEL:
        default: 1
        description: 'max'
        required: true

jobs:
  matrix_job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: ${{ fromJSON(github.event.inputs.MAX_PARALLEL) }}
      matrix: 
        job_name: ['one', 'two', 'three', 'four', 'five']
    steps:
      - name: create_output
        run: |
          echo "::set-output name=my_output::${{ matrix.job_name }}"
      - name: ${{ steps.create_output.output.my_output }}
        run: echo "This steps name is dynamically set to '${{ matrix.job_name }}'"

  aggregator:
    runs-on: ubuntu-latest
    needs: [ matrix_job ]
    steps:
      - uses: actions/github-script@v3
        with:
          script: | 
            let { data: joblist } = await github.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.run_id }}
            });
            console.log(JSON.stringify(joblist));

