name: "pull as aggregator"

on:
  workflow_dispatch:
  push:

jobs:
  get_pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var comment = "";
            try {
              const { data: result } = await github.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: 14
              });
              var id = result.number;
              const { data: list } = await github.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: id
              });  
              for(var index in list) {
                comment += list[index].body;
              }
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: id
                body: comment
              });
            } catch (err) {
              core.setFailed(`Request has failed with error ${err}`);
            }