name: "pull as aggregator"

on:
  workflow_dispatch:

jobs:
  get_pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var comment = "";
            try {
              const result = await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: 14
              });
              var id = result.number;
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`);
            }