name: "pull as aggregator"

on:
  workflow_dispatch:
  push:

jobs:
  get_pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var comment = "";
            try {
              const { data: result } = await github.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: 14
              });
              console.log(result);
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`);
            }