name: "Ansible: az-account-creation"
# This workflow expects that you have created a branch which will become the target of workspace updates.  
#                  -----------        DO NOT RUN THIS FROM MASTER!      -----------
# Typically, the workflow would be: 1) create branch 2) push updates to account-specific host variable file
# 3) run this job to update/rebuild the Terraform workspace(s) based upon changes to the account.yml file

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define environment: [dev | prod]'
        required: true
        default: 'dev'
      target_type:
        description: 'Target type [account | environment]'
        required: true
        default: 'account'
      account_name:
        description: 'The name of the account. Only required when target_type = account'
        required: false
        default: 'ucsfit-customer1'
      workspace:
        description: 'Workspace to rebuild [all | identity | network | security | storage | operations]'
        required: true
        default: 'identity'
      account_type:
        description: 'Account Type: [hipaa | it-svcs]'
        required: true
        default: 'hipaa'

jobs:
  determine_accounts_to_run:
    name: "determine_accounts"
    runs-on: ubuntu-latest
    outputs:
      customer_files: ${{ steps.inventory_path.outputs.customer_files }}
    steps:
      # Determine the path to the customer yml file based on inputs and iterpolation
      - name: Determine Inventory Path
        id: inventory_path
        run:  |
          env=${{ github.event.inputs.environment }}
          path="./inventories/$env/group_vars/accounts"
          cd $path
          files=($(find -E . -type f -regex "^.*$"))          
          echo "::set-output name=customer_files::$files"
        if: ${{ github.event.inputs.target_type == 'account' && ((steps.extract_branch.outputs.branch != 'master') && (steps.extract_branch.outputs.branch != 'main')) }}

      # Print the inventory path to the output
      - name: Display Inventory Path
        id: debug_inventory_path
        run: echo "${{ steps.inventory_path.outputs.inventory_path }}"
        if: ${{ github.event.inputs.target_type == 'account' && ((steps.extract_branch.outputs.branch != 'master') && (steps.extract_branch.outputs.branch != 'main')) }}
