name: "test pipeline exit codes"

on:
  workflow_dispatch:
  
jobs:
  test_pipeline_exitcodes_succeed:
    name: Succeeds
    runs-on: ubuntu-latest
    steps:
      - run: |
          true | true
          #exit ${PIPESTATUS[0]}
      
  test_pipeline_exitcodes_succeed2:
    name: Succeeds2
    runs-on: ubuntu-latest
    steps:
      - run: |
          false | true
          #exit ${PIPESTATUS[1]}
          
  test_pipeline_exitcodes_fails:
    name: Fails
    runs-on: ubuntu-latest
    steps:
      - run: |
          true | true
          #exit ${PIPESTATUS[1]}
