name: "test pipeline exit codes"

on:
  workflow_dispatch:
  
jobs:
  test_pipeline_exitcodes_succeed:
    name: Succeeds
    runs-on: ubuntu-latest
    steps:
      - run: |
          true | false
          exit ${PIPESTATUS[0]}
      
  test_pipeline_exitcodes_fail:
    name: Fails
    runs-on: ubuntu-latest
    steps:
      - run: |
          true | false
          exit ${PIPESTATUS[1]}
