name: workflow-caller
on: workflow_dispatch

jobs:
  caller1:
    uses: tjanuario/actions_demo/.github/workflows/workflow_called.yml@${{ github.head_ref }}
    with:
      variable: My variable
  caller2:
    uses: tjanuario/actions_demo/.github/workflows/workflow_called.yml@${{ github.head_ref }}
    with:
      variable: Another variable