name: workflow_called

on: 
  workflow_call:
    inputs:
      variable:
        type: string
        required: true

jobs:
  called:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.variable }}"
