name: workflow-caller
on: workflow_dispatch

jobs:
  caller1:
    uses: tjanuario/actions_demo/.github/workflows/workflow_called@e49c4fc3c6e36f93c46bc074c31970f257e27d94
    with:
      variable: My variable
  caller2:
    uses: tjanuario/actions_demo/.github/workflows/workflow_called@e49c4fc3c6e36f93c46bc074c31970f257e27d94
    with:
      variable: Another variable